name: essbpats_conference_app
description: ESSB & PATS Conference Mobile Application
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  
  # Navigation
  go_router: ^13.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  
  # QR & Barcode
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  # qr_code_scanner: ^1.0.1  <- علقنا عليه
  
  # Phone Number
  intl_phone_field: ^3.2.0
  
  # Excel
  excel: ^4.0.2
  
  # PDF & Certificate
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  mobile_scanner: ^7.1.3

  
  
  # Images & Media
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  
  # URL & Links
  url_launcher: ^6.2.3
  
  # Maps
  google_maps_flutter: ^2.5.3
  
  # Storage
  shared_preferences: ^2.2.2
  
  # HTTP
  http: ^1.2.0
  dio: ^5.4.0
  
  # Utils
  flutter_countdown_timer: ^4.1.0
  intl: ^0.19.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
    - assets/data/
    - assets/images/board_members/
    - assets/images/conference_banner.png
    